name: Update blog posts
on:
  schedule:
    - cron: "0 */12 * * *"   # twice daily
  workflow_dispatch:
jobs:
  blog:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://athrael.net/rss.xml,https://athrael.net/feed.xml,https://athrael.net/index.xml"
          max_post_count: 5
